use fit2101;

DROP TABLE IF EXISTS `Hour_Logged`;
DROP TABLE IF EXISTS `Task_Tag`;
DROP TABLE IF EXISTS `Sprint_Task`;
DROP TABLE IF EXISTS `Task`;
DROP TABLE IF EXISTS `Tag`;
DROP TABLE IF EXISTS `Sprint`;
DROP TABLE IF EXISTS `User`;
DROP VIEW IF EXISTS `Task_View`;
DROP VIEW IF EXISTS `Sprint_Task_View`;
DROP VIEW IF EXISTS `Sprint_View`;
DROP VIEW IF EXISTS `User_Hours_Logged`;

